package com.example.textbook.data

import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.ForeignKey

@Entity(tableName = "files")
data class FileEntity(
    @PrimaryKey val path: String,
    val name: String,
    val extension: String,
    val content: String, // Base content (usually the latest full version or initial)
    val lastModified: Long,
    val isReadOnly: Boolean = false
)

@Entity(
    tableName = "versions",
    foreignKeys = [
        ForeignKey(
            entity = FileEntity::class,
            parentColumns = ["path"],
            childColumns = ["filePath"],
            onDelete = ForeignKey.CASCADE
        )
    ]
)
data class VersionEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val filePath: String,
    val versionName: String,
    val timestamp: Long,
    val delta: String, // Patch string generated by java-diff-utils
    val addedCount: Int,
    val removedCount: Int
)

@Entity(tableName = "crash_recovery")
data class CrashRecoveryEntity(
    @PrimaryKey val filePath: String,
    val content: String,
    val timestamp: Long
)
